version: '3.8'

networks:
    nginx-php-composer-mariadb:

services:
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "${NGINX_PORT_HTTP}:80"
            - "${NGINX_PORT_HTTPS}:443"
        volumes:
            - ./:/application
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-service
            - db-service
        networks:
            - nginx-php-composer-mariadb
    php-service:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
            args:
                - GIT_MAIL=${GIT_MAIL}
                - GIT_USERNAME=${GIT_USERNAME}
        container_name: php-container
        ports:
            - "${PHP_PORT}:3306"
        volumes:
            - ./:/application
        restart: always
        depends_on:
            - db-service
        networks:
            - nginx-php-composer-mariadb
    db-service:
        image: mariadb:latest
        container_name: db-container
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - ./docker/database:/var/lib/mysql
        restart: restart: on-failure
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        networks:
            - nginx-php-composer-mariadb
